# Generated by Django 5.1.4 on 2025-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messmateuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='messmateuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='messmateuser',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='messmateuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='messmateuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='messmateuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messmateuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messmateuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='messmateuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
