# Generated by Django 5.1.4 on 2025-02-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mess_owner', '0007_alter_mess_mess_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='mess_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField()),
                ('mess_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mess_owner.mess')),
            ],
        ),
    ]
