# Generated by Django 5.1.4 on 2025-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess_menu',
            name='from_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='mess_menu',
            name='to_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
