# Generated by Django 5.1.4 on 2025-02-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_mess_menu_from_time_mess_menu_to_time'),
        ('mess_owner', '0010_rename_uid_mess_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_menu',
            name='mess_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mess_owner.mess'),
        ),
    ]
