# Generated by Django 5.1.4 on 2025-01-25 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_owner', '0002_rename_mess_photo_mess_mess_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='mess_ratings',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
