# Generated by Django 5.1.4 on 2025-01-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_owner', '0003_alter_mess_mess_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='mess_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
