# Generated by Django 5.1.4 on 2025-01-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_owner', '0005_alter_mess_mess_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='mess_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
