# Generated by Django 5.1.4 on 2025-02-06 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_owner', '0007_alter_mess_mess_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
