# Generated by Django 5.1.4 on 2025-02-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_owner', '0008_mess_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess',
            old_name='user_id',
            new_name='uid',
        ),
    ]
